# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: experiments and essais
email: jeromegoodrich@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jeromegoodrich.com" # the base hostname & protocol for your site
twitter_username: J_roams_well
github_username: JeromeGoodrich

# Build settings
markdown: kramdown
